library(shiny)
library(plotly)
library(shinythemes)
df <- read.csv("https://raw.githubusercontent.com/info201a-su23/exploratory-analysis-p02-Doryi/main/MoviesOnStreamingPlatforms.csv")

ui <- navbarPage("Analyzing Various Streaming Platforms",
                 theme = shinytheme("journal"),
                 tabPanel("Introduction",
                          HTML("<img src='https://cdn.technadu.com/wp-content/uploads/2020/04/Netflix-Amazon-Prime-Hulu-Disney-Plus-Logos.png' alt='Streaming services' style='width: 600px; height: auto;'>"),
                          h1(div(style = "color: green;", "Analysis of Movie Offerings from Hulu, Netflix, Disney and Prime")),
                          h2("Overview"),
                          p("With the rise of streaming platforms, the entertainment and media access has undergone tremendous changes. Streaming platforms have completely changed how we access and enjoy content, allowing us to quickly see many movies, TV programs, documentaries, etc. With the intensification of competition, various streaming platforms aim to differentiate themselves via unique offerings."),
                          p("This study aims to analyze exclusivity, movie reviews, age ratings and move release years from major streaming platforms (Netflix, Hulu, Disney, and Prime Video) to understand their relative advantages and disadvantages."),
                          h2("Research Questions"),
                          strong("How does the content library of each streaming platform compare in terms of type diversity, and how do the movie release years compare across platforms?"),
                          p("Overall, Prime Video leads the competition in terms of its total number of offerings, especially for newer releases. Netflix is a close runner up for newer movies as well. However, Disney has a substantial catalog of vintage movies which sometimes exceed Prime's offerings in certain older years."),
                          strong("What age does each platform cater to based on their average age rating?"),
                          p("Disney absolutely focuses on a younger audience with over 50% of their movies being rated for 7+. This is very unlike the other three platforms that only offer ~10% of their movies to this younger audience. Hulu has the largest target on a mature audience with over 1/3 of its movies being 18+. Meanwhile, Netflix and Prime are somewhere in the middle with a slight bias towards a mature audience."),
                          strong("How do the average movie ratings differ across the various platforms?"),
                          p("Overall, all 4 platforms roughly have a similar distribution. However, Disney and Hulu lead the competition with relatively the least poorly rated movies. Meanwhile, Netflix offers a large range of good and bad movies. Unfortunately, Prime false short and has the lowest median and lacks excellent movies."),
                          h2("Challenges and Limitations"),
                          p("One challenge is that data set includes too few characteristics of platforms. It does not show the price range of streaming services. It does not have the user experience of different platforms. Moreover, I think the data set lacks categories of movies such as comedy, thriller, and so on. The categories of movies allow us to analyze which category of movies are popular on each platform. If we do not know the most popular movie category in each platform, we cannot compare strengths and weaknesses in terms of content between different platforms."),
                          p("Another limitation would be the inability to consider other streaming platforms that could be equally competitive, such as YouTube Plus or HBO Max. This could have an effect on the implications previously mentioned as it will be difficult for users of the data to gain a full perspective of the various offerings in the market. For example, finding that one of the platforms from our analysis has the newest movies doesn’t necessarily mean that this platform has the newest movies within the entire market."),
                          p("There are no substantial ethical concerns regarding this study or data."),
                          h2("About the Data"),
                          p("The data was collected by Ruchi Bhaia who is a product marketing manager and data scientist at HP Pittsburgh. It was generated by directly scraping the information off of the different streaming platforms. The data was collected to show on which platform people can find their chosen movies. It is also collected to explore the relationship between movies of different age groups and platforms that include these movies. The data includes 9515 observations and 11 attributes."),
                          h2("Source"),
                          tags$style(
                            HTML(".link-button { display: inline-block; padding: 10px 20px; background-color: #007bff; color: #fff; text-decoration: none; border-radius: 4px; }")
                          ),
                          
                          a(
                            href = "https://www.kaggle.com/datasets/ruchi798/movies-on-netflix-prime-video-hulu-and-disney",
                            class = "link-button",
                            "Visit data source"
                          )
                          ),
                          
                
                 tabPanel("Diversity of Streaming Platforms",
                          h1("Diversity of Streaming Platforms"),
                          p(HTML("This graph was created to answer: <strong>How does the content library of each streaming platform compare in terms of type diversity, and how do the movie release years compare across platforms?</strong>")),
                          p("This is accomplished by creating a bar graph to visualize the number of movies released by various streaming platforms from 1914 to 2021. When we compare the growth trend of the number of movies on various platforms over the years, we can better understand the different diversity of movie libraries and the development of platforms. By observing the number of movies per year, we can also glimpse the preferences and release strategies of various platforms for new and old movies. This trend analysis can reveal the unique orientations of various platforms in selecting movie content, which may reflect their understanding of audience preferences and the relative popularity of different theme films in the market."),
                          
                          sidebarLayout(
                            sidebarPanel(
                              h3("Options for Graph"),
                              sliderInput(inputId = "Year",
                                          label = "Select the year:",
                                          min = min(df$Year, na.rm = TRUE),
                                          max = max(df$Year, na.rm = TRUE),
                                          value = max(df$Year, na.rm = TRUE),
                                          step = 1),
                              numericInput(inputId = "SelectedYear",
                                           label = "Enter a year:",
                                           value = max(df$Year, na.rm = TRUE),
                                           min = min(df$Year, na.rm = TRUE),
                                           max = max(df$Year, na.rm = TRUE))
                            ),
                        
                            mainPanel(
                              plotlyOutput(outputId = "interactive_chart"),
                              textOutput(outputId = "MovieCountOutput")
                            )
                            
                          ),
                          p("This bar chart reveals significant differences in the number of movies across streaming platforms. Prime Video and Netflix have more films released over the years, while Disney+ and Hulu have relatively few. This reflects the differences in content supply among different platforms and may also reflect their positioning and audience groups. The chart also shows that the movie libraries of Prime Video and Netflix mainly focus on recent movies, with fewer containing classic movies from nearly 2000 years. In contrast, Disney+ and Hulu's movie library specifically includes movies from 10 years ago, and they have more classic movies than the other two platforms. This allows users to visually see the differences in time dimensions of each platform, helping them choose the platform that suits their taste. Through this visualization approach, users can better understand the diversity of movies on various streaming platforms and their differences in movie production over the years.")
                          
                 ),
                 tabPanel("Movie Age Rating",
                          h1("Movie Age Rating"),
                          p(HTML("This graph was created to answer: <strong>What age does each platform cater to based on their average age rating?</strong>")),
                          p("This is accomplished by creating a pie chart to visualize the distribution of Rotten Tomatoes ratings for each platform."),
                          
                          sidebarLayout(
                            sidebarPanel(
                              selectInput(
                                inputId = "platform_input",
                                label = "Select streaming platform to analyze:",
                                choices = list(
                                  "Netflix" = "Netflix",
                                  "Disney+" = "Disney",
                                  "Prime Video" = "Prime",
                                  "Hulu" = "Hulu"
                                ),
                                selected = "Netflix",
                                multiple = FALSE
                              )
                            ),
                            mainPanel(
                              plotlyOutput(outputId = "pie_chart")
                            )
                          ),
                          br(),
                          p("Streaming platforms often differentiate themselves by targeting unique content to specific demographics. This is important for users to decide which platform is best suited for their age group, and also for platforms as it can show the advantages they hold and thus change their business strategy."),
                          br(),
                          p("For answering the question 'What is the percentage of different age ratings for each platform?', the best chart for visualization is a pie chart. The pie chart is designed to show the parts of a whole, helping us understand how movie age ratings are distributed across a platform's entire movie collection. By looking at the pie chart, we can immediately determine which age-rated movies are most and least common on each platform. The pie chart's clear visualization of movie age ratings allows users to discern which platforms align with their viewing preferences, and stakeholders can extract strategic insights about content positioning and targeting. A balanced distribution of age ratings indicates a platform's intention to cater to a wide audience. Conversely, a platform dominated by a particular age category might be targeting a specific demographic. From a business perspective, understanding these distributions can inform licensing decisions, content strategies, and marketing approaches.")
                 ),
                 tabPanel("Distribution of Rating",
                          h1("Distribution of Rating"),
                          p(HTML("This graph was created to answer: <strong>How do the average movie ratings differ across the various platforms?</strong>")),
                          p("This is accomplished by creating a histogram to visualize the distribution of movie age ratings by platform."),
                          
                          sidebarLayout(
                            sidebarPanel(
                              selectInput(inputId = "platform",
                                          label = "Select Platform:",
                                          choices = c("Disney", "Netflix", "Hulu", "Prime.Video"),
                                          selected = "Disney"),
                              sliderInput(inputId = "bins",
                                          label = "Number of bins:",
                                          min = 1,
                                          max = 40,
                                          value = 20)
                            ),
                            mainPanel(
                              plotlyOutput(outputId = "distPlot"),
                              verbatimTextOutput("graphDescription")
                            )
                          ),
                          p("The histogram plot shows the distribution of Rotten Tomatoes ratings for each platform. It tries to understand whether there is any difference in the rating distribution between platforms. Also, it tries to know whether the distribution is robust to changes in the number of bins.")
                 ),
                 tabPanel("Summary",
                          h1(div(style = "color: red;", "Key Takeaways")),
                          h2("Takeaway 1"),
                          p("Compared to Netflix, Hulu and Prime, Disney differentiates itself from the competitions by offering a unique set of titles targeted at a smaller audience. Although their total collection falls short of their competitors’, they are able to compensate for this by excelling in niche categories. For example, 50.4% of their movies are rated for 7+, which is 5 times higher than the other services. Meanwhile, they are far less invested in categories that their competitors already dominate, such as 18+ titles. "),
                          h2("Takeaway 2"),
                          p("Overall, Prime Video leads the competition overall in terms of the total number of movies available to its users. For example, they had 105 movies released in 2010. Meanwhile, the runner up was Netflix with just 64, which is a drastic difference. It is worth noting that Prime seems to be falling short of their latest offerings. In 2020, they had just 204 movies. However, Netflix far exceeded this with 478 movies. It’s possible that Prime Video could lose market share in the future if this trend continues long term. "),
                          h2("Takeaway 3"),
                          p("Among Hulu, Netflix, Disney and Prime, the distribution of Rotten Tomato ratings is relatively similar, which was very surprising. All of the streaming services roughly shared a normal distribution with a median slightly above 50 percent. However, Prime did slightly fall short to its competition, which could be because of their vast library discussed in the second takeaway. Perhaps they are more focused on the quantity of their movies rather than quality. Meanwhile, Disney, which has the smallest catalogue, slightly exceeds the competition in movie quality. "),
                          h1("Important Insights"),
                          p("From this analysis, the most important thing we learned was how each streaming platforms attempts to differentiate itself from the other in order to stay competitive. They want to segment themselves in a way that somebody would benefit from subscribing to multiple services simultaneously, each with their own strong points. For example, Hulu might have the highest quality movies, but their catalogue is still far inferior to Prime."),
                          p("The broader implication of this market segmentation is that these streaming services will get better and better as their catalogues expand. To the end user, this is highly beneficial as we get to see a larger diversity of movies from the same streaming service. At the same time, it might become more necessary to hold multiple subscriptions if these streaming services continue to differentiate themselves.  ")
                          
                          )
)
